# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build GeyserMC

on:
  push:
    branches: [ modified ]
  pull_request:
    branches: [ modified ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Downloads all the needed submodule
      run: git submodule update --init --recursive
    - name: Build with Maven
      run: mvn clean install
    - name: Geyser-Spigot Upload Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: Geyser-Spigot
        path: bootstrap/spigot/target/*.jar
    - name: Geyser-Velocity Upload Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: Geyser-Velocity
        path: bootstrap/velocity/target/*.jar
    - name: Geyser-BungeeCord Upload Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: Geyser-BungeeCord
        path: bootstrap/bungeecord/target/*.jar
    - name: Geyser-Sponge Upload Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: Geyser-Sponge
        path: bootstrap/sponge/target/*.jar
    - name: Geyser-Standalone Upload Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: Geyser-Standalone
        path: bootstrap/standalone/target/*.jar
